tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/versions'
brew 'app-engine-python'
brew 'git'
brew 'git-lfs'
brew 'git-extras'
brew 'cheat'
brew 'ctags'
brew 'emacs'
brew 'sqlite'
brew 'openssl'
brew 'python'
brew 'ffmpeg'
brew 'git-secrets'
brew 'gnupg2'
brew 'heroku'
brew 'hub'
brew 'keybase'
brew 'kommit'
brew 'lua'
brew 'luajit'
brew 'mongodb'
brew 'node'
brew 'python3'
brew 'speedtest_cli'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'macvim', args: ['with-override-system-vim']
brew 'youtube-dl'
brew 'zsh'
brew 'ruby'
brew 'fpp'
brew 'mas'
brew 'certbot'
brew 'neofetch'
brew 'emojify'
brew 'ghi'
brew 'findutils'
brew 'pyenv'
brew 'peco'
brew 'doxygen'
brew 'yarn'
brew 'go'
brew 'diff-so-fancy'
brew 'httpie'
brew 'jsonlint'
cask 'flux'
cask 'dash'
cask 'keyboard-cleaner'
mas 'Affinity Photo', id: 824183456
mas 'Xcode', id: 497799835
mas 'Affinity Designer', id: 824171161
mas 'Magnet', id: 441258766
mas '1Password', id: 443987910
mas 'Keka', id: 470158793
mas 'PopClip', id: 445189367
mas 'Slack', id: 803453959
mas 'Sip', id: 507257563
